name: HeliOS Build & Run Unit Tests

on:

  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

  workflow_dispatch:

jobs:
  build-test: 
    runs-on: ubuntu-22.04
    
    outputs:
      stdout: ${{ steps.run-test.outputs.stdout }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Install build essentials...
        shell: bash
        run: |
          sudo apt -qq update
          sudo apt -y install build-essential

      - name: Build HeliOS unit tests...
        shell: bash
        run: gcc -fdiagnostics-color=always -O0 -ggdb -std=c89 -Wall -Wextra -I ${{github.workspace}}/src -DPOSIX_ARCH_OTHER -DCONFIG_MEMORY_REGION_SIZE_IN_BLOCKS=0x1C20u -DCONFIG_ENABLE_SYSTEM_ASSERT -o ${{github.workspace}}/extras/test/bin/test ${{github.workspace}}/src/*.c ${{github.workspace}}/extras/test/src/test.c 

      - name: Run HeliOS unit tests...
        id: run-test
        shell: bash
        run: ${{github.workspace}}/extras/test/bin/test

      - name: Try reading output
        shell: bash
        run: echo ${{steps.run-test.outputs.stdout}}